def list():
  return [
    {'name': 'Sam Bosch', 'spotify_id': '2a78oeD5iYBG0RNRL9l7cw', 'genres': ['Indie', 'Folk'], 'notes': 'Played with Sam at Larimer. Political so bre ready for stuff'},
    {'name': 'The Time Release Formula', 'spotify_id': '2Szxx1p7kYM0zyGBhhqslh', 'genres': ['Indie', 'Rock'], 'notes': 'Played with them at Larimer'},
    {'name': 'Kenny Cornbread', 'spotify_id': '6EtevT6rvFRObvVs2O7N13', 'genres': ['alternative country']},
    {'name': 'Ultralow', 'spotify_id': '6aY8Wr3YyUFTaYYpb1z9GN', 'genres': ['Lounge']},
    {'name': 'Becca Jay', 'spotify_id': '21ZrVHkswlETtAHLwDYeH4'},
    {'name': 'Sarah Adams', 'spotify_id': '6uorDvCD6x4sq1hFR29xHe', 'genres': ['Indie', 'Folk'], 'social_links': 'https://www.instagram.com/sarah.adams.music', 'notes': 'Played with Srah at Globe 2024'},
    {'name': 'Motel Frunz', 'spotify_id': '5twWfHZVVFu10LHLtY3hfX', 'genres': ['Indie', 'Rock', 'Prog'], 'notes': 'Jaylen\'s band'},
    {'name': 'Polkadot Palace', 'spotify_id': '0z1meEMrEEOevjqKUPvTCo', 'genres': ['Panda Rock', 'Rock']},
    {'name': 'Chophaus', 'spotify_id': '3xxH57oX4sJrf9GOIbSvZs', 'genres': ['Metal']},
    {'name': 'Bobcat Rabbitfoot', 'spotify_id': '6eHpgRQq8vu2qU07Hjy9UW', 'genres': ['Cowpunk', 'Jam']},
    {'name': 'Holden Reed', 'spotify_id': '75LJFwaUS0p8A8vu3H7sgK', 'genres': ['Indie', 'Folk', 'Rock']},
    {'name': 'Coldridge', 'spotify_id': '31JxBlLWItP3OGyooBoar7', 'genres': ['Prog'], 'notes': 'Played Moe\'s Oct 2024 show'},
    {'name': 'Lucy Daydream', 'spotify_id': '0RQEMnWcCrVW4vkPFbAVsg', 'genres': ['Singer Songwriter']},
    {'name': 'Jeremiah Fraites', 'spotify_id': '3g2R76efKeTTrhOMz1oJly', 'genres': ['Indie']},
    {'name': 'Trevor Hall', 'spotify_id': '3RMHexittaAZkf8zukkZB8', 'genres': ['Future Folk']},
    {'name': 'Morning Bear', 'spotify_id': '7eMLPJmuTaWqfIjtEAqcQ4', 'genres': ['Indie']},
    {'name': 'Clay Street Unit', 'spotify_id': '0HmpQ609wnu7isR6i96CWb', 'genres': ['Southern Folk', 'Country']},
    {'name': 'Kiltro', 'spotify_id': '27CC3tpq7WQR25M03jKTZm', 'genres': ['Indie', 'Latin Folk']},
    {'name': 'Drunken Hearts', 'spotify_id': '65L4dreDHXasm3Qb6idKiH', 'genres': ['Dark Country']},
    {'name': 'SunSquabi', 'spotify_id': '1CLLPNftraxuTDyTd6hn3J', 'genres': ['Electronica'], 'notes': 'Cool sound'},
    {'name': 'The Dollhouse Thieves', 'spotify_id': '5gU6A6dbQiPI6TUhGprvE0', 'genres': ['Indie', 'Folk']},
    {'name': 'Wildermiss', 'spotify_id': '7K9fyLw4RPBp8PIFkif2eB', 'genres': ['Pop', 'Punk']},
    {'name': 'Bellhoss', 'spotify_id': '0C4Cx3s5LpuMig1Kc34mTx', 'genres': ['Folk', 'Punk']},
    {'name': 'Blankslate', 'spotify_id': '6J9FZLDMZz2YK0riSBuon3', 'genres': ['Indie', 'Pop']},
    {'name': 'May Be Fern', 'spotify_id': '630MKbRM1ewBYBt3C9TTtB', 'genres': ['Indie', 'Rock']},
    {'name': 'Corsicana', 'spotify_id': '39ydxfWgeQxEiGP9JxlT0s', 'genres': ['Indie', 'Shoegaze']},
    {'name': 'Gasoline Lollipops', 'spotify_id': '590hKyYZLEQQLmIgl9ErTl', 'genres': ['Folk', 'Indie', 'Americana']},
    {'name': 'Lo Fi Ho Hum', 'spotify_id': '5grRqETCFGI0zzrsquHN0a', 'genres': ['Indie']},
    {'name': 'Megan Burtt', 'spotify_id': '7vTmj10GHcTm40U6CsIkbP', 'genres': ['Folk']},
    {'name': 'The Milk Blossoms', 'spotify_id': '4IzboIkcMBTePqFrg8Zamz', 'genres': ['Indie', 'Pop']},
    {'name': 'Angel Corsi', 'spotify_id': '1eAGkhEx1yfvFzbyWGfgmM', 'genres': ['Folk', 'Singer Songwriter']},
    {'name': 'Antonio Lopez', 'spotify_id': '3q1hLZjfSE9QS0u86fiD0l', 'genres': ['Singer Songwriter']},
    {'name': 'Conrad Mata', 'spotify_id': '4VrVHMu0fHu8PoaVoYJrFZ', 'genres': ['Experimental', 'Rock']},
    {'name': 'Isaac Martinez', 'spotify_id': '5ciGXfH8GOQRBFZiwbSqNS', 'genres': ['Indie']},
    {'name': 'Andy Tran', 'spotify_id': '790Img4URfwiERemcN9zbs', 'genres': ['Indie']},
    {'name': 'The Beach People', 'spotify_id': '4B1sVXuhDIFM6ltmRNIbNr', 'genres': ['Indie', 'Pop']},
    {'name': 'Big Dopes', 'spotify_id': '59TmedKid8gXn5vRe5KYTq', 'notes': 'Kinda cheesey', 'genres': ['Indie']},
    {'name': 'Frail Talk', 'spotify_id': '7stmp1OR4yaVInBIXIeKBf', 'genres': ['Indie']},
    {'name': 'Graham Good and the Painters', 'spotify_id': '5anRy2kwFKkwtewYlCX0RZ', 'genres': ['Jam Rock']},
    {'name': 'Jeff Cramer', 'spotify_id': '23PTKUIwqzguERw43L9GYe', 'notes': 'Fucking great stuff', 'genres': ['Indie']},
    {'name': 'Sun Way Street', 'spotify_id': '2izH50d9suTRrx44cPxPMO', 'genres': ['Indie', 'Folk']},
    {'name': 'Trevor Michael', 'spotify_id': '0TofxMDhVDmJPKcuabYUV0', 'genres': ['Folk']},
    {'name': 'Velvet Daydream', 'spotify_id': '28x6FrmmwiH5r7K41Xwxik', 'genres': ['Classic Rock']},
    {'name': 'Brianna Straut', 'spotify_id': '3cO0qeB9mzpOI232OSZBdY', 'genres': ['Indie', 'Country']},
    {'name': 'Britt Devens', 'spotify_id': '6lmnc7nwT9e6z36dDG4LXB', 'genres': ['Country']},
    {'name': 'Chase Cavanaugh', 'spotify_id': '6DH1kypdObaGWIcKEefQEQ', 'genres': ['Indie']},
    {'name': 'Sophia Eliana', 'spotify_id': '04SVS79AeZgWLZMHVjcwn3', 'genres': ['Indie', 'Folk']},
    {'name': 'Yugs', 'spotify_id': '4GjfiH7lIFZp0X5SF3LbEP', 'genres': ['Indie', 'Hip Hop']},
    {'name': 'American Culture', 'spotify_id': '6OaSE468GGX1xWqex449FP', 'genres': ['Indie']},
    {'name': 'Elektric Animals', 'spotify_id': '7mXNzN8Qsvjt254lhRunKc', 'genres': ['Indie']},
    {'name': 'Little Trips', 'spotify_id': '4wi006S2tBJwgHZtxuUyTz', 'genres': ['Dream Pop']},
    {'name': 'The Mañanas', 'spotify_id': '0FGyNRcUfWjBuMFvJ6WaN2', 'genres': ['Indie', 'Pop']},
    {'name': 'Silver & Gold', 'spotify_id': '3p3TLOpkXs5Pnrk43fvbI6', 'genres': ['Indie']},
    {'name': 'Slow Caves', 'spotify_id': '4P50NzjBhqd2dr6CQ8asjl', 'notes': 'Good band', 'genres': ['Indie']},
    {'name': 'Sponsored Content', 'spotify_id': '4mKzjnpOK98dqPfRNtOceQ', 'genres': ['Indie']},
    {'name': 'Sunstoney', 'spotify_id': '3oLuCerqscBRek7Nw9mpqL', 'genres': ['Indie']},
    {'name': 'Horse Bitch', 'spotify_id': '1Zt2Apekc6uieOsLkf7M0v', 'notes': 'UMS set was amazing', 'genres': ['Indie', 'Emo Honkeytonk']},
    {'name': 'Whisper States', 'spotify_id': '5JzGxBtfcCl8oJTF0GRPq5', 'genres': ['Indie', 'Folk']},
    {'name': 'A Place For Owls', 'spotify_id': '5LjHrLecrhxnVJYlqDzSe2', 'genres': ['Indie', 'Emo']},
    {'name': 'Porcelain Twin', 'spotify_id': '0pv9SuWJY3LaEaCcjBUd1W', 'genres': ['Indie'], 'notes': 'These guys post a lot in r/denvermusic'},
    {'name': 'Luna Sol', 'spotify_id': '31u3refS0tKDq8JFs4rgVx', 'genres': ['Rock']},
    {'name': 'Strangers Only', 'spotify_id': '307gPxXz2kQkaZd9N0kJ4a', 'genres': ['Indie']},
    {'name': 'Elder Grown', 'spotify_id': '2goH9cMI15q2lSTHCkrZCO', 'genres': ['Indie', 'Funk', 'Jam']},
    {'name': 'Phooey', 'notes': 'Played Moe\'s Oct 2024 show', 'genres': ['Jam Rock']},
    {'name': 'Sullen Mary', 'genres': ['Doom', 'Folk']},
    {'name': 'The Street Deacons', 'notes': 'Played Moe\'s Oct 2024 show', 'genres': ['Blues', 'Jazz', 'Rock']},
    {'name': 'Becca Jay', 'spotify_id': '6aY8Wr3YyUFTaYYpb1z9GN', 'genres': ['Indie'], 'notes': 'Dave found them at Todd\'s Cervantes show'}
  ]
